# Generated by Django 2.1.7 on 2019-02-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('nama_mall', models.CharField(max_length=255)),
                ('lokasi_mall', models.CharField(max_length=255)),
                ('deskripsi_mall', models.TextField()),
            ],
        ),
    ]
