# Generated by Django 2.1.7 on 2019-02-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='map_park',
            field=models.TextField(max_length=1000),
        ),
    ]
